ci(tests): add retry in tests

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -160,12 +160,23 @@ jobs:
             echo "Testing $component metrics endpoint"
             for ip in $(kubectl get po -l "app.kubernetes.io/component=$component" -n kuik-system -o jsonpath='{range .items[*]}{.status.podIP}{"\n"}{end}')
             do
-               response=$(kubectl run curl-pod --image=curlimages/curl --rm -ti --quiet --restart=Never -- curl -s -o /dev/null -w "%{http_code}\n" http://$ip:8080/metrics)
-               if [[ $response -ge 200 && $response -lt 300 ]]; then
-                  echo "HTTP status code $response is valid for $ip"
-               else
-                  echo "HTTP status code $response is not valid for $ip"
-                  exit 1
+               attempts=0
+               success=false
+               while [[ $attempts -lt 3 && $success == false ]]
+               do
+                   response=$(kubectl run curl-pod --image=curlimages/curl --rm -ti --quiet --restart=Never -- curl -s -o /dev/null -w "%{http_code}\n" http://$ip:8080/metrics)
+                   if [[ $response -ge 200 && $response -lt 300 ]]; then
+                        echo "HTTP status code $response is valid for $ip"
+                        success=true
+                   else
+                        echo "HTTP status code $response is not valid for $ip"
+                        ((attempts++))
+                        sleep 5
+                   fi
+               done
+               if [[ $success == false ]]; then
+                      echo "Failed after 3 attempts for $ip"
+                      exit 1
                fi
             done
           done
