ci: wip upgrade tests

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -74,7 +74,7 @@ jobs:
             ${{ env.HARBOR_URL }}/${{ env.HARBOR_REPO }}:${{ env.VERSION }}-alpine
 
   e2e_install:
-    name: Tests End-to-End on K8s (Fresh install)
+    name: Tests e2e on K8s (Fresh install)
     needs:
       - build
     runs-on: ubuntu-22.04
@@ -100,7 +100,7 @@ jobs:
       - name: Run cert-manager installation
         run: |
           kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
-          kubectl wait pods -n cert-manager -l app.kubernetes.io/instance=cert-manager --for condition=Ready --timeout=30s
+          kubectl wait pods -n cert-manager -l app.kubernetes.io/instance=cert-manager --for condition=Ready --timeout=90s
 
       - name: Set up chart-testing
         uses: helm/chart-testing-action@v2.6.1
@@ -136,15 +136,20 @@ jobs:
             --set controllers.image.tag=$VERSION --set proxy.image.tag=$VERSION \
             --set controllers.image.repository=$HARBOR_IMAGE --set proxy.image.repository=$HARBOR_IMAGE \
             --set controllers.imagePullSecrets[0].name=harbor-secret --set proxy.image.imagePullSecrets[0].name=harbor-secret  --debug
-          kubectl wait pods -n kuik-system -l app.kubernetes.io/instance=kube-image-keeper --for condition=Ready --timeout=30s
+          kubectl wait pods -n kuik-system -l app.kubernetes.io/instance=kube-image-keeper --for condition=Ready --timeout=90s
+          helm history kube-image-keeper -n kuik-system
 
       - name: Run end-to-end tests
         run: |
           set -euo pipefail
           kubectl create deploy nginx --image=nginx:stable-alpine --replicas=2
+          kubectl rollout status deploy nginx 
           kubectl wait deployment nginx --for condition=Available=True --timeout=30s
-          echo "kubectl get cachedimages"
+          echo "kubectl get cachedimage"
           kubectl get cachedimages
+          echo "kubectl get repository"
+          kubectl get repository
+          ## Check if our test image is cached
           if [ $(kubectl get cachedimages docker.io-library-nginx-stable-alpine -o json | jq ".status.isCached") ];
           then
               if [ $(kubectl get cachedimages docker.io-library-nginx-stable-alpine -o json | jq ".status.usedBy.count") -eq 2 ];
@@ -158,6 +163,15 @@ jobs:
               echo "Error: image cached status is false"
               exit 1
           fi
+          ## Check repository status
+          if kubectl get repository docker.io-library-nginx -o json | jq '.status.phase == "Ready"' ;
+          then
+              echo "Found repository"
+          else
+              echo "Error: image repository status is not Ready"
+              exit 1
+          fi
+          ## Check for kuik's components metrics
           for component in proxy controllers
           do 
             echo "Testing $component metrics endpoint"
@@ -187,7 +201,7 @@ jobs:
           done
 
   e2e_upgrade:
-    name: Tests End-to-End on K8s (Upgrade)
+    name: Tests e2e on K8s (Upgrade)
     needs:
       - build
       - e2e_install
@@ -258,16 +272,24 @@ jobs:
           helm upgrade --install kube-image-keeper -n kuik-system --create-namespace ./helm/kube-image-keeper \
             --set controllers.image.tag=$VERSION --set proxy.image.tag=$VERSION \
             --set controllers.image.repository=$HARBOR_IMAGE --set proxy.image.repository=$HARBOR_IMAGE \
-            --set controllers.imagePullSecrets[0].name=harbor-secret --set proxy.image.imagePullSecrets[0].name=harbor-secret  --debug
-          kubectl wait pods -n kuik-system -l app.kubernetes.io/instance=kube-image-keeper --for condition=Ready --timeout=30s
+            --set controllers.imagePullSecrets[0].name=harbor-secret --set proxy.image.imagePullSecrets[0].name=harbor-secret --wait --debug
+          kubectl rollout status deploy kube-image-keeper-controllers -n kuik-system
+          kubectl rollout status ds kube-image-keeper-proxy -n kuik-system
+          kubectl get po -n kuik-system
+          kubectl wait pods -n kuik-system -l app.kubernetes.io/instance=kube-image-keeper --for condition=Ready --timeout=90s
+          helm history kube-image-keeper -n kuik-system
 
       - name: Run end-to-end tests
         run: |
           set -euo pipefail
           kubectl create deploy nginx --image=nginx:stable-alpine --replicas=2
+          kubectl rollout status deploy nginx 
           kubectl wait deployment nginx --for condition=Available=True --timeout=30s
-          echo "kubectl get cachedimages"
+          echo "kubectl get cachedimage"
           kubectl get cachedimages
+          echo "kubectl get repository"
+          kubectl get repository
+          ## Check if our test image is cached
           if [ $(kubectl get cachedimages docker.io-library-nginx-stable-alpine -o json | jq ".status.isCached") ];
           then
               if [ $(kubectl get cachedimages docker.io-library-nginx-stable-alpine -o json | jq ".status.usedBy.count") -eq 2 ];
@@ -281,6 +303,15 @@ jobs:
               echo "Error: image cached status is false"
               exit 1
           fi
+          ## Check repository status
+          if kubectl get repository docker.io-library-nginx -o json | jq '.status.phase == "NotReady"' ;
+          then
+              echo "Found repository"
+          else
+              echo "Error: image repository status is not Ready"
+              exit 1
+          fi
+          ## Check for kuik's components metrics
           for component in proxy controllers
           do 
             echo "Testing $component metrics endpoint"
